name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  emacsdir: ".emacs.d"

jobs:
  setup-emacs:
    env:
      TERM: xterm-256color
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 29.3
          - 29.4
    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Check out code
        uses: actions/checkout@v3
        with:
           path: ${{ env.emacsdir }}

      - name: Cache packages
        uses: actions/cache@v4
        env:
          cache-name: cache-emacs-packages
        with:
          path: ${{ env.emacsdir }}/straight
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.emacs_version }}-${{ hashFiles('straight/versions/*') }}

      - name: Deploy Emacs configuration
        run: ${{ env.emacsdir }}/bin/emacs-config deploy --yes

      - name: Test Emacs configuration
        run: ${{ env.emacsdir }}/bin/emacs-config test

      - name: Emacs logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: emacs-${{ matrix.emacs_version }}-logs
          path: ${{ env.emacsdir }}/.local/etc/logs/
