name: CI

on:
  push:
    branches:
      - master
      - fix_ci
  pull_request:
    branches:
      - master

jobs:
  setup-emacs:
    env:
      TERM: xterm-256color
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 29.3
          - 29.4
    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache packages
        uses: actions/cache@v3
        env:
          cache-name: cache-emacs-packages
        with:
          path: straight
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('straight/versions/*') }}

      - name: Deploy Emacs configuration
        run: bin/emacs-config deploy --yes

      - name: Test Emacs configuration
        run: bin/emacs-config test

      - name: Emacs logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Emacs logs
          path: .local/etc/logs/
